name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cc: [ clang, gcc ]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: env CFLAGS="-Wpedantic -Wall -Werror" cmake -B build && make -C build
        env:
          CC: /usr/bin/${{ matrix.cc }}
